apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: w5v1p8afv-nodejs 
  janus-idp.io/tekton: w5v1p8afv-nodejs
  backstage.io/kubernetes-id: w5v1p8afv-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: w5v1p8afv-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml